---
- name: Install docker and required software 
  hosts: all 
  tasks: 
      - name: install python pip 
        apt:
          name: python3-pip
          state: present 
          update_cache: yes 

      - name: Download and install docker and also docker-py 
        shell: "{{item}}"
        with_items:
           - curl -fsSL https://get.docker.com -o install-docker.sh
           - sudo sh install-docker.sh
