---

- name: create user on all servers 
  hosts: web
  tasks: 
     - name: User creation 
       user:
          name: bob
          password: redhat 
          uid: 1256
          comment: "a normal user"
          shell: /bin/bash 
          home: /tmp/bob

...
           
