---
- name: Capture OS info 
  hosts: web 
  tasks: 
    - name: capture os name 
      debug: 
        msg: "{{ansible_distribution}}"
    - name: capture os version name
      debug: 
        msg: "{{ansible_distribution_version}}" 
    - name: capture os major version number 
      debug: 
        msg: "{{ansible_distribution_major_version}}" 
...  
