---
- name: configuring Tomcat10 
  hosts: all 
  tasks:
    - name: install tomcat10 
      apt:
        name: tomcat10 
        state: present 
        update_cache: yes 
    - name: install tomcat10-admin
      apt:
        name: tomcat10-admin
        state: present 
        update_cache: yes 
    - name: Copy tomcat-user.xml file 
      copy:
        src: tomcat-users.xml 
        dest: /etc/tomcat10
    - name: change port of tomcat from 8080 to 9090
      replace: 
        regexp: 8080
        replace: 9090 
        path: /etc/tomcat10/server.xml 
    - name: restart tomcat 
      service: 
        name: tomcat10
        state: restarted
    - name: Pause for 1 minute 
      pause: 
        minutes: 1
    - name: check tomcat on node1 
      uri:
        url: http://13.233.137.75:9090
        status_code: 200   
    - name: check tomcat on node2
      uri:
        url: http://65.0.75.174:9090
        status_code: 200   
...
