---
# vars file for tomcat
pkg1: tomcat10
pkg2: tomcat10-admin
state1: present 
state2: restarted
cache1: yes
cache2: no 
file1: tomcat-users.xml 
dest1: /etc/tomcat10
port1: 8080
port2: 9090
path1: /etc/tomcat10/server.xml
min: 1
server1: "http://172.31.12.173"
server2: "http://172.31.7.169"
status1: 200 
